# Generated by Django 6.0.6 on 2026-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('pcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('area_sqkm', models.FloatField(default=0)),
                ('geometry', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('pcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('area_sqkm', models.FloatField(default=0)),
                ('geometry', models.JSONField(default=dict)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='governorates.governorate')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
            },
        ),
    ]
