# Generated by Django 6.0.6 on 2026-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='مجهول', max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
    ]
