# Generated by Django 6.0.6 on 2026-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governorates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDataItem',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hood', 'حي'), ('lane', 'حارة')], max_length=10)),
                ('district_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='governorates.district')),
            ],
            options={
                'verbose_name': 'بيانات ميدانية',
                'verbose_name_plural': 'البيانات الميدانية',
            },
        ),
    ]
