# Generated by Django 6.0.6 on 2026-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='متجر', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('rating', models.FloatField(default=4.5)),
                ('delivery_fee', models.IntegerField(default=500)),
                ('open', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='accounts.merchantprofile')),
            ],
            options={
                'verbose_name': 'متجر',
                'verbose_name_plural': 'المتاجر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(default='وحدة', max_length=50)),
                ('image', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.5)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
    ]
