# Generated by Django 6.0.6 on 2026-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'متجر', 'verbose_name_plural': 'المتاجر'},
        ),
    ]
